train_kwargs:
  enable_MBPO: false
  policy: TD3 
  env_name: 'random_generate_td3_simple_correctmaxact'
  experiment_name: 'SimpleEnv_HER_correctmaxact'
  seed: 0
  load_model: ""
  max_timesteps: 1000000
  start_timesteps: 2500
  batch_size: 256
  eval_freq: 2500
  save_model: True
  expl_noise: 0.1
  model_rollout_batch_size: 250
  num_rollouts_per_step: 400
  rollout_horizon: 1
  model_update_freq: 5000
  num_gradient_updates: 20
  percentage_real_transition: 0.2 
  seed_coeff: 0 
  seed_init: 2
  goal_condition: True
  random: True
  HER: True
  HER_k: 4
  random_init_everytime: False
TD3_kwargs:
  discount: 0.99
  tau: 0.01
  policy_noise: 0.2
  noise_clip: 0.5
  policy_freq: 2
model_kwargs:
  num_networks: 7
  num_elites: 5
  model_lr: 0.001